"""
QR-bootstrapped device pairing.

Replaces a long-lived DEVICE_REGISTRATION_SECRET with a short-lived,
single-use X25519 key exchange: the pairing QR carries this server's
ephemeral public key, never a shared secret, so a LAN eavesdropper who
captures every packet of the registration POST still can't complete the
exchange — they never saw the QR.

  1. create_pairing_session()  -- server generates an ephemeral X25519
     keypair + random token, stores {token: privateKey, expiresAt}, and
     returns the QR payload: token, this server's public key, and its
     public URL (so the app never needs a URL typed in beforehand).
  2. The app scans the QR (or pastes the same payload), generates its own
     ephemeral X25519 keypair, derives a transport key via ECDH + HKDF,
     and POSTs back {token, appPublicKey, nonce, ciphertext} where the
     ciphertext is AES-256-GCM({apnsDeviceTokenHex, deviceName,
     pushEncryptionKey}) under the transport key. The push-encryption key
     is generated by the app itself — it never crosses the wire, even
     encrypted, in the direction that matters (server did not need to
     mint it and hand it over, like the old flow did).
  3. complete_pairing_session() re-derives the same transport key from the
     stored private key + the app's public key, decrypts, and deletes the
     session (single-use — a retried or duplicated request can't replay
     it).

Session storage goes through state_store (SQLite) rather than a
module-level dict: the app runs under multiple gunicorn workers
(app/Dockerfile, --workers 3) that don't share process memory, so a dict
here would make pairing fail whenever the QR-issuing request and the
registration request happen to land on different workers.

A compromised state DB already exposes every device's long-term push key
(state category "devices"), so a pairing session's ~90s-lived private key
sitting in the same DB adds no new exposure — it's strictly less
sensitive than what's already stored there.
"""

import base64
import io
import json
import secrets
import time

import qrcode
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

from . import state_store

PAIRING_SESSION_TTL_SECONDS = 90
HKDF_INFO = b"privatepush-pairing-v1"


class PairingSessionError(Exception):
    """Any pairing failure the route should turn into a 400. The message
    is safe to return to the client — it never contains key material."""


def _prune_expired_sessions(sessions):
    now = time.time()
    return {
        token: session for token, session in sessions.items()
        if session["expiresAt"] > now
    }


def create_pairing_session(server_public_url):
    sessions = _prune_expired_sessions(state_store.read_state("pairingSessions"))

    server_private_key = X25519PrivateKey.generate()
    token = secrets.token_urlsafe(16)
    expires_at = time.time() + PAIRING_SESSION_TTL_SECONDS

    sessions[token] = {
        "serverPrivateKey": base64.b64encode(
            server_private_key.private_bytes_raw()
        ).decode(),
        "expiresAt": expires_at,
    }
    state_store.write_state("pairingSessions", sessions)

    return {
        "v": 1,
        "server": server_public_url,
        "token": token,
        "pub": base64.b64encode(server_private_key.public_key().public_bytes_raw()).decode(),
        "expiresAt": expires_at,
    }


def _derive_transport_key(private_key, peer_public_key_base64, token):
    peer_public_key = X25519PublicKey.from_public_bytes(
        base64.b64decode(peer_public_key_base64)
    )
    shared_secret = private_key.exchange(peer_public_key)
    return HKDF(
        algorithm=hashes.SHA256(), length=32, salt=token.encode(), info=HKDF_INFO
    ).derive(shared_secret)


def complete_pairing_session(token, app_public_key_base64, nonce_base64, ciphertext_base64):
    sessions = _prune_expired_sessions(state_store.read_state("pairingSessions"))
    session = sessions.get(token)
    if session is None:
        raise PairingSessionError("pairing code expired or already used")

    # Single-use: remove before doing any decryption work, so a retried or
    # duplicated request (e.g. two devices racing the same QR) can't reuse it.
    del sessions[token]
    state_store.write_state("pairingSessions", sessions)

    try:
        server_private_key = X25519PrivateKey.from_private_bytes(
            base64.b64decode(session["serverPrivateKey"])
        )
        transport_key = _derive_transport_key(server_private_key, app_public_key_base64, token)
        plaintext_json = AESGCM(transport_key).decrypt(
            base64.b64decode(nonce_base64), base64.b64decode(ciphertext_base64), None
        )
        return json.loads(plaintext_json)
    except PairingSessionError:
        raise
    except Exception as decryption_error:
        raise PairingSessionError("could not decrypt pairing payload") from decryption_error


def render_qr_data_uri(payload_text):
    """A scannable PNG for the /pair web page, inlined so the route never
    needs to serve or clean up a temp file."""
    qr_image = qrcode.make(payload_text)
    buffer = io.BytesIO()
    qr_image.save(buffer, format="PNG")
    return "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode()


def print_ascii_qr(payload_text):
    """For `flask --app server pair` — lets a terminal-only admin pair a
    device without opening a browser."""
    qr = qrcode.QRCode(border=1)
    qr.add_data(payload_text)
    qr.make(fit=True)
    qr.print_ascii(invert=True)
